 

services:
  whpg:
    image: whpg:latest
    container_name: whpg-app
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true      
    networks:
      - proxy    
    ports:
      - '${PORT}:3000'
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@whpg-pgdb:${POSTGRES_PORT}/db?schema=public"
      WEBHOOK_BASE_URL: ${WEBHOOK_BASE_URL}
    depends_on:
      - pgdb

  pgdb:
    image: postgres:15
    container_name: whpg-pgdb
    restart: always
    networks:
      - backend-whpg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  postgres_data:




networks:
  proxy:
    external: true   
  backend-whpg:  