 

services:
  whpg:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    # depends_on:
    #   - db

#   db:
#     image: postgres:15
#     restart: always
#     networks:
#       - backend-whpg
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: mydb
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

# volumes:
#   postgres_data:




# networks:
#   proxy:
#     external: true   
#   backend-whpg:  