 

services:
  whpg:
    image: xcaptdz/whpg:latest
    container_name: whpg-app
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true      
    networks:
      - proxy
      # - backend-whpg    
    ports:
      - '${PORT}:3000'
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@10.0.10.100:5434/db?schema=public"
      WEBHOOK_BASE_URL: ${WEBHOOK_BASE_URL}

    depends_on:
      - pgdb


# docker exec -it whpg-app  scripts/init-db.sh



  pgdb:
    image: postgres:15
    container_name: whpg-pgdb
    restart: always
    networks:
      - proxy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /home/xcapt/stacks/.volumes/pgdb/data:/var/lib/postgresql/data

    ports:
      - "${POSTGRES_PORT}:5432"

# volumes:
#   whpg_app:




networks:
  proxy:
    external: true   
  backend-whpg:  