 # docker exec -it whpg-app  npx prisma db push
  

services:
  whpg:
    image: xcaptdz/whpg:latest
    container_name: whpg-app
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true      
    networks:
      - proxy
      - backend   
    ports:
      - '${PORT}:3000'
    environment:

      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresdb:5432/db?schema=public"
      WEBHOOK_BASE_URL: ${WEBHOOK_BASE_URL}

    depends_on:
      - postgresdb


  postgresdb:
    image: postgres:15
    container_name: whpg-postgresdb
    security_opt:
      - no-new-privileges:true    
    restart: always
    networks:
      - backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /home/xcapt/stacks/.volumes/whpg-postgresdb/data:/var/lib/postgresql/data


networks:
  proxy:
    external: true   
  backend:  